s=" i love computer "
print(s.upper())
print(s.lower())
print(s.capitalize())
print(s.title())
print(s.count("t"))
print(s.endswith("r"))
print(s.find("love"))
k=s.replace("love","hate")
print(k.upper())
print(s.isupper())
print(s.islower())
a="hi mani"
print(a.isalnum())
print(a.isalpha())
print(a.split())
print(a.split(" "))
print(s.partition(" "))